apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-api
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-api
  template:
    metadata:
      labels:
        app: music-api
    spec:
      containers:
        - name: music-api
          image: music-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://user:pass@postgres:5432/musicdb
