apiVersion: v1
kind: Service
metadata:
  name: music-api
  namespace: airflow
spec:
  selector:
    app: music-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
