apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
    - name: debug
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - mountPath: /music-categorizer-data
          name: music-categorizer-pvc
      tty: true
      stdin: true
  volumes:
    - name: music-categorizer-pvc
      persistentVolumeClaim:
        claimName: music-categorizer-pvc
  restartPolicy: Never

# kubectl exec -it debug-pod -- sh