apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-categorizer-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/music-categorizer-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-categorizer-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
