apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-categorizer-pv
  namespace: airflow
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/music-categorizer-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-categorizer-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: hostpath
